## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df = application_df.drop(columns=["EIN","NAME"])

In [ ]:
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = ["T9", "T13", "T12", "T2", "T25", "T14","T29", "T15", "T17"]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification = application_df["CLASSIFICATION"].value_counts()
classification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
filter = classification.loc[classification > 1]
filter

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification.loc[classification < 1800]
classifications_to_replace = classifications_to_replace.to_frame()
classifications_to_replace.reset_index(inplace=True)
classifications_to_replace = classifications_to_replace["index"]

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"]
X = application_df.drop(columns="IS_SUCCESSFUL")

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`

numerical_columns = X.select_dtypes(include=['int','float64']).columns
categorical_columns = X.select_dtypes(include=['object','boolean']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('nominal', OneHotEncoder(handle_unknown='ignore'), categorical_columns),
        ('numeric', StandardScaler(), numerical_columns)
])

In [ ]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT
31183,T3,Independent,C1200,Preservation,Trust,1,0,N,5000
15770,T3,Independent,C1000,Preservation,Trust,1,0,N,5000
21523,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000
13573,T3,Independent,C1000,Preservation,Trust,1,0,N,5000
20380,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000
...,...,...,...,...,...,...,...,...,...
16850,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,333518
6265,T3,Independent,C3000,Preservation,Trust,1,0,N,5000
11284,T3,Independent,C1200,Preservation,Trust,1,0,N,5000
860,T3,CompanySponsored,C1000,Preservation,Association,1,0,N,5000
15795,T3,Independent,C1000,Preservation,Trust,1,0,N,5000

In [ ]:
# Create a StandardScaler instances
# scaler = StandardScaler()

# Fit the StandardScaler
# X_scaler = scaler.fit(X_train)

# Scale the data
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

X_train = preprocessor.fit_transform(X_train).toarray()
X_test  = preprocessor.transform(X_test).toarray()

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential([
    # First hidden layer
  tf.keras.layers.Dense(units=80, activation='relu', input_shape=(X_train.shape[1],)),
    # Second hidden layer
  tf.keras.layers.Dense(units=30, activation='relu'),
    # Output layer
  tf.keras.layers.Dense(units=1, activation='sigmoid')
])

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Train the model
training_data = nn.fit(X_train, y_train, epochs=100)

Epoch 1/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7413
Epoch 2/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7402
Epoch 3/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7411
Epoch 4/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7417
Epoch 5/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7406
Epoch 6/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7412
Epoch 7/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5316 - accuracy: 0.7412
Epoch 8/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7410
Epoch 9/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7411
Epoch 10/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7411
Epoch 11/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7415
Epoch 12/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7411
Epoch 13/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7406
Epoch 14/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7412
Epoch 15/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 16/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7415
Epoch 17/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7413
Epoch 18/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5336 - accuracy: 0.7408
Epoch 19/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5309 - accuracy: 0.7412
Epoch 20/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7411
Epoch 21/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7419
Epoch 22/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7417
Epoch 23/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7413
Epoch 24/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7412
Epoch 25/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7412
Epoch 26/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7415
Epoch 27/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7419
Epoch 28/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7416
Epoch 29/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7420
Epoch 30/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7411
Epoch 31/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5306 - accuracy: 0.7410
Epoch 32/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7412
Epoch 33/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5304 - accuracy: 0.7420
Epoch 34/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7407
Epoch 35/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7427
Epoch 36/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7415
Epoch 37/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7419
Epoch 38/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7420
Epoch 39/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7424
Epoch 40/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5306 - accuracy: 0.7418
Epoch 41/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7423
Epoch 42/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5301 - accuracy: 0.7421
Epoch 43/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7421
Epoch 44/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7423
Epoch 45/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7418
Epoch 46/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5300 - accuracy: 0.7416
Epoch 47/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7415
Epoch 48/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7412
Epoch 49/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7422
Epoch 50/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7426
Epoch 51/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7423
Epoch 52/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7423
Epoch 53/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7418
Epoch 54/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7421
Epoch 55/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7426
Epoch 56/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7418
Epoch 57/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7428
Epoch 58/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7422
Epoch 59/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7418
Epoch 60/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7423
Epoch 61/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7422
Epoch 62/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7432
Epoch 63/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7421
Epoch 64/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7419
Epoch 65/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7421
Epoch 66/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7424
Epoch 67/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7425
Epoch 68/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7413
Epoch 69/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7420
Epoch 70/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7432
Epoch 71/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7415
Epoch 72/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7421
Epoch 73/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7423
Epoch 74/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7419
Epoch 75/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7419
Epoch 76/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7422
Epoch 77/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7423
Epoch 78/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7423
Epoch 79/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7415
Epoch 80/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7418
Epoch 81/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7425
Epoch 82/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7420
Epoch 83/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7426
Epoch 84/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7431
Epoch 85/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7427
Epoch 86/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7421
Epoch 87/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7418
Epoch 88/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7424
Epoch 89/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7425
Epoch 90/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7428
Epoch 91/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7422
Epoch 92/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7431
Epoch 93/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.7431
Epoch 94/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7429
Epoch 95/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7423
Epoch 96/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7424
Epoch 97/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7410
Epoch 98/100
858/858 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7432
Epoch 99/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7419
Epoch 100/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7425

In [1]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

NameError: name 'nn' is not defined

In [ ]:
# Export our model to HDF5 file
nn.save("charity_data_model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(